<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230815213223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784FC0A1DCB');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784150428AC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77842F375BC1');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F778444126792');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77847460B703');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784895C34FD');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77849E3CF8DC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784C875A6A');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784E2F01BBC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784FF280E4B');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F778418819110');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784351083F0');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77844DF70BC3');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77847BD29E03');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F778493BB3419');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77849F8D0CA');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784D170C740');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784EA409230');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F778414D4E9E');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F778424002A8');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77844099A264');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784607EA73D');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77847E17D074');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F77849BB615C');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784C3D910EF');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_C42F7784DC43AE2E');
        $this->addSql('DROP INDEX uniq_c42f7784fc0a1dcb ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5FC0A1DCB ON bodygraph (sun_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784ea409230 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5EA409230 ON bodygraph (earth_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77847460b703 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A57460B703 ON bodygraph (north_node_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784c3d910ef ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5C3D910EF ON bodygraph (south_node_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784d170c740 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5D170C740 ON bodygraph (moon_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784150428ac ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5150428AC ON bodygraph (mercury_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77849e3cf8dc ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A59E3CF8DC ON bodygraph (venus_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784dc43ae2e ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5DC43AE2E ON bodygraph (mars_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77842f375bc1 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A52F375BC1 ON bodygraph (jupiter_design_id)');
        $this->addSql('DROP INDEX uniq_c42f7784351083f0 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5351083F0 ON bodygraph (saturn_design_id)');
        $this->addSql('DROP INDEX uniq_c42f778493bb3419 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A593BB3419 ON bodygraph (uranus_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77844099a264 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A54099A264 ON bodygraph (neptune_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77847e17d074 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A57E17D074 ON bodygraph (pluto_design_id)');
        $this->addSql('DROP INDEX uniq_c42f77849bb615c ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A59BB615C ON bodygraph (sun_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f7784e2f01bbc ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5E2F01BBC ON bodygraph (earth_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f778444126792 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A544126792 ON bodygraph (north_node_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f778418819110 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A518819110 ON bodygraph (south_node_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f7784ff280e4b ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5FF280E4B ON bodygraph (moon_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f7784607ea73d ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5607EA73D ON bodygraph (mercury_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f77844df70bc3 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A54DF70BC3 ON bodygraph (venus_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f7784c875a6a ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5C875A6A ON bodygraph (mars_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f77847bd29e03 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A57BD29E03 ON bodygraph (jupiter_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f7784895c34fd ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A5895C34FD ON bodygraph (saturn_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f778414d4e9e ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A514D4E9E ON bodygraph (uranus_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f77849f8d0ca ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A59F8D0CA ON bodygraph (neptune_personality_id)');
        $this->addSql('DROP INDEX uniq_c42f778424002a8 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1E4C9A524002A8 ON bodygraph (pluto_personality_id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784FC0A1DCB FOREIGN KEY (sun_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784150428AC FOREIGN KEY (mercury_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77842F375BC1 FOREIGN KEY (jupiter_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F778444126792 FOREIGN KEY (north_node_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77847460B703 FOREIGN KEY (north_node_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784895C34FD FOREIGN KEY (saturn_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77849E3CF8DC FOREIGN KEY (venus_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784C875A6A FOREIGN KEY (mars_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784E2F01BBC FOREIGN KEY (earth_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784FF280E4B FOREIGN KEY (moon_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F778418819110 FOREIGN KEY (south_node_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784351083F0 FOREIGN KEY (saturn_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77844DF70BC3 FOREIGN KEY (venus_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77847BD29E03 FOREIGN KEY (jupiter_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F778493BB3419 FOREIGN KEY (uranus_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77849F8D0CA FOREIGN KEY (neptune_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784D170C740 FOREIGN KEY (moon_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784EA409230 FOREIGN KEY (earth_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F778414D4E9E FOREIGN KEY (uranus_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F778424002A8 FOREIGN KEY (pluto_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77844099A264 FOREIGN KEY (neptune_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784607EA73D FOREIGN KEY (mercury_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77847E17D074 FOREIGN KEY (pluto_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F77849BB615C FOREIGN KEY (sun_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784C3D910EF FOREIGN KEY (south_node_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_C42F7784DC43AE2E FOREIGN KEY (mars_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph_tag DROP FOREIGN KEY FK_F372CF044BD2A4C0');
        $this->addSql('DROP INDEX IDX_F372CF044BD2A4C0 ON bodygraph_tag');
        $this->addSql('DROP INDEX `primary` ON bodygraph_tag');
        $this->addSql('ALTER TABLE bodygraph_tag DROP FOREIGN KEY FK_F372CF04BAD26311');
        $this->addSql('ALTER TABLE bodygraph_tag CHANGE report_id bodygraph_id INT NOT NULL');
        $this->addSql('ALTER TABLE bodygraph_tag ADD CONSTRAINT FK_E73CECFF4AD10DC FOREIGN KEY (bodygraph_id) REFERENCES bodygraph (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_E73CECFF4AD10DC ON bodygraph_tag (bodygraph_id)');
        $this->addSql('ALTER TABLE bodygraph_tag ADD PRIMARY KEY (bodygraph_id, tag_id)');
        $this->addSql('DROP INDEX idx_f372cf04bad26311 ON bodygraph_tag');
        $this->addSql('CREATE INDEX IDX_E73CECFFBAD26311 ON bodygraph_tag (tag_id)');
        $this->addSql('ALTER TABLE bodygraph_tag ADD CONSTRAINT FK_F372CF04BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gate CHANGE subtitle subtitle VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bodygraph_tag DROP FOREIGN KEY FK_E73CECFF4AD10DC');
        $this->addSql('DROP INDEX IDX_E73CECFF4AD10DC ON bodygraph_tag');
        $this->addSql('DROP INDEX `PRIMARY` ON bodygraph_tag');
        $this->addSql('ALTER TABLE bodygraph_tag DROP FOREIGN KEY FK_E73CECFFBAD26311');
        $this->addSql('ALTER TABLE bodygraph_tag CHANGE bodygraph_id report_id INT NOT NULL');
        $this->addSql('ALTER TABLE bodygraph_tag ADD CONSTRAINT FK_F372CF044BD2A4C0 FOREIGN KEY (report_id) REFERENCES bodygraph (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_F372CF044BD2A4C0 ON bodygraph_tag (report_id)');
        $this->addSql('ALTER TABLE bodygraph_tag ADD PRIMARY KEY (report_id, tag_id)');
        $this->addSql('DROP INDEX idx_e73cecffbad26311 ON bodygraph_tag');
        $this->addSql('CREATE INDEX IDX_F372CF04BAD26311 ON bodygraph_tag (tag_id)');
        $this->addSql('ALTER TABLE bodygraph_tag ADD CONSTRAINT FK_E73CECFFBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gate CHANGE subtitle subtitle VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5FC0A1DCB');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5EA409230');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A57460B703');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5C3D910EF');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5D170C740');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5150428AC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A59E3CF8DC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5DC43AE2E');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A52F375BC1');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5351083F0');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A593BB3419');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A54099A264');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A57E17D074');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A59BB615C');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5E2F01BBC');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A544126792');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A518819110');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5FF280E4B');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5607EA73D');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A54DF70BC3');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5C875A6A');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A57BD29E03');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A5895C34FD');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A514D4E9E');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A59F8D0CA');
        $this->addSql('ALTER TABLE bodygraph DROP FOREIGN KEY FK_1E4C9A524002A8');
        $this->addSql('DROP INDEX uniq_1e4c9a57e17d074 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77847E17D074 ON bodygraph (pluto_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5351083f0 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784351083F0 ON bodygraph (saturn_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a524002a8 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F778424002A8 ON bodygraph (pluto_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a59e3cf8dc ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77849E3CF8DC ON bodygraph (venus_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5895c34fd ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784895C34FD ON bodygraph (saturn_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5c3d910ef ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784C3D910EF ON bodygraph (south_node_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a54df70bc3 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77844DF70BC3 ON bodygraph (venus_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5fc0a1dcb ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784FC0A1DCB ON bodygraph (sun_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a518819110 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F778418819110 ON bodygraph (south_node_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a59bb615c ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77849BB615C ON bodygraph (sun_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a593bb3419 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F778493BB3419 ON bodygraph (uranus_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5dc43ae2e ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784DC43AE2E ON bodygraph (mars_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a514d4e9e ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F778414D4E9E ON bodygraph (uranus_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5d170c740 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784D170C740 ON bodygraph (moon_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5c875a6a ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784C875A6A ON bodygraph (mars_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5ea409230 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784EA409230 ON bodygraph (earth_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5ff280e4b ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784FF280E4B ON bodygraph (moon_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5e2f01bbc ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784E2F01BBC ON bodygraph (earth_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a54099a264 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77844099A264 ON bodygraph (neptune_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a52f375bc1 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77842F375BC1 ON bodygraph (jupiter_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a59f8d0ca ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77849F8D0CA ON bodygraph (neptune_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5150428ac ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784150428AC ON bodygraph (mercury_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a57bd29e03 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77847BD29E03 ON bodygraph (jupiter_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a57460b703 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F77847460B703 ON bodygraph (north_node_design_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a5607ea73d ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F7784607EA73D ON bodygraph (mercury_personality_id)');
        $this->addSql('DROP INDEX uniq_1e4c9a544126792 ON bodygraph');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C42F778444126792 ON bodygraph (north_node_personality_id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5FC0A1DCB FOREIGN KEY (sun_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5EA409230 FOREIGN KEY (earth_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A57460B703 FOREIGN KEY (north_node_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5C3D910EF FOREIGN KEY (south_node_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5D170C740 FOREIGN KEY (moon_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5150428AC FOREIGN KEY (mercury_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A59E3CF8DC FOREIGN KEY (venus_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5DC43AE2E FOREIGN KEY (mars_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A52F375BC1 FOREIGN KEY (jupiter_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5351083F0 FOREIGN KEY (saturn_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A593BB3419 FOREIGN KEY (uranus_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A54099A264 FOREIGN KEY (neptune_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A57E17D074 FOREIGN KEY (pluto_design_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A59BB615C FOREIGN KEY (sun_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5E2F01BBC FOREIGN KEY (earth_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A544126792 FOREIGN KEY (north_node_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A518819110 FOREIGN KEY (south_node_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5FF280E4B FOREIGN KEY (moon_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5607EA73D FOREIGN KEY (mercury_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A54DF70BC3 FOREIGN KEY (venus_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5C875A6A FOREIGN KEY (mars_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A57BD29E03 FOREIGN KEY (jupiter_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A5895C34FD FOREIGN KEY (saturn_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A514D4E9E FOREIGN KEY (uranus_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A59F8D0CA FOREIGN KEY (neptune_personality_id) REFERENCES gate (id)');
        $this->addSql('ALTER TABLE bodygraph ADD CONSTRAINT FK_1E4C9A524002A8 FOREIGN KEY (pluto_personality_id) REFERENCES gate (id)');
    }
}
