dashboard:
    path: /dashboard
    controller: App\Controller\Admin\DashboardController::index
home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      route: 'dashboard'
